version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "${HOST_PORT}:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env.prod
    # Remove depends_on since the database service is no longer in this compose file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/healthz', (r) => { if (r.statusCode !== 200) throw new Error('Health check failed') }).on('error', (e) => { console.error(e.message); process.exit(1); })"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  # Remove the database service since the database is installed on the server, not in Docker

volumes:
  postgres_data_prod: